### ISSUE TITLE
LinuxMint: Sciencelab refuses to connect due to insufficient rights

### ISSUE THREAD

**Issue by JohnnnyJohnnny** [fossasia/pslab-python#123]
The hardware registers itself as serial device. Unfortunately serial devices are part of the group dialout and the default user on my system (and probably other) doesn't have access rights to it. 

So, you need root rights or you need to add your user to the dialout group:
`sudo usermod -a -G dialout MY_USER_NAME`

I don't know if Mint is special in this case, but I would recommend to add something in the installation documentation.

**Comment by bessman** [comment]
Hi Johnnny, thank you for the report.

Manually adding your user to the dialout group should not be necessary, and is likely required because the udev rules were not installed correctly. Looking at it now, I  think the Makefile included with PSL actually installs the rules incorrectly; it creates a file in /lib/udev/rules.d/ called 99-pslab, which udev will ignore because it does not end with .rules. Renaming it to 99-pslab.rules makes /dev/ttyACM0 read and writable by any user, not just members of dialout.
