### ISSUE TITLE
Should repository be renamed to pslab-python

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-python#41]
There are several components to PSLab. Currently this repository is holding the code for the python project. Therefore it would probably be better to rename this repository to pslab-python.

**Comment by wavicles** [comment]
@mariobehling Yes. it will be better to rename the repo and make necessary changes. @jithinbp ??

**Comment by jithinbp** [comment]
Yes, i agree. We should rename to PSLab-Python or something more specific.
Please do the needful

Thanks,
Jithin

On 7 Apr 2017 10:45 p.m., "Praveen (Gnovi)" <notifications@github.com>
wrote:

@mariobehling <https://github.com/mariobehling> Yes. it will be better to
rename the repo and make necessary changes. @jithinbp
<https://github.com/jithinbp> ??

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fossasia/pslab/issues/41#issuecomment-292596982>, or mute
the thread

**Comment by mariobehling** [comment]
Done. Thanks.
