### ISSUE TITLE
Role of RPi.GPIO library in MF522.py

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-python#54]
[Here](https://github.com/fossasia/pslab-python/blob/development/PSL/SENSORS/MF522.py#L166), 22 pin of Raspberry pi is set high. I can't get the use of the RPi.GPIO library in MF522.py.

**Comment by viveksb007** [comment]
@akarshan96 PSLab device is compatible with raspberry pi too. As this is python communication library, and Pi has OS based on Linux. So this particular sensor might have been tested with Pi.

**Comment by jithinbp** [comment]
Hi,
It looks like partially ported code from RPi, and the function
'MFRC522_Init()' should be deleted.
I have tested the RFID reader with this library , and the relevant
initialization registers are configured in the __init__ routine of the
Python library itself.
The RPi.GPIO import should also be removed. Please compare with the library
<https://github.com/jithinbp/SEELablet/blob/master/SEEL/SENSORS/MF522.py>
that I have verified .

The GUI also needs improvement because the RFID reader is a little slow to
respond, and the GUI should show progress indicators and such. But for now
it
can't be prioritized unless you have the reader and some smart cards.
I had a card, but I misused the rules for writing data, and wrote to
registers that apparently ruined the card.
 Hope that helps.

**Comment by akarshan96** [comment]
@jithinbp Thanks, I will make required changes.
